[package]
name = "plugin_registrar"
version = "0.1.0"
edition = "2024"

[dependencies]
dynamic_message_extension = { path = "../../libs/dynamic_message_extension" }
uuid.workspace = true
sqlx.workspace = true
time.workspace = true
rand.workspace = true
wakuwaku.workspace = true
kanau.workspace = true
rkyv.workspace = true
redis.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true