//! Plugin registrar service.
//!
//! Orchestrates registration (atomically writing the plugin row plus its
//! declared tools, skills, namespaces, and dependencies), de-registration,
//! namespace-based service discovery, plugin listing, the cluster-wide tool
//! catalog, and the JWT-secret lookup the plugin-auth layer is generic over.

use dynamic_message_extension::plugin_message::FindJwtSecretRequest;
use kanau::processor::Processor;
use rand::distr::SampleString;
use tracing::instrument;
use uuid::Uuid;
use wakuwaku::{Error, sqlx::DatabaseProcessor};

use crate::entities::db::plugin::{
    DeletePlugin, FindPluginById, FindPluginJwtSecret, ListPlugins, NewPluginSkill, NewPluginTool,
    PluginEntity, PluginMetadataEntity, RegisterPluginRow,
};
use crate::entities::db::plugin_namespace::FindPluginIdByNamespace;
use crate::entities::db::plugin_tool::{ListAllPluginTools, PluginToolEntity};

/// Length, in characters, of a generated plugin JWT secret.
const JWT_SECRET_LENGTH: usize = 48;

/// Service entry point for everything plugin-registration related.
#[derive(Clone)]
pub struct PluginRegistrarService {
    pub db: DatabaseProcessor,
}

/// Generate a random, 48-character alphanumeric JWT signing secret.
fn generate_secret() -> String {
    rand::distr::Alphanumeric.sample_string(&mut rand::rng(), JWT_SECRET_LENGTH)
}

/// Derive the AMQP exchange name the cluster uses to address a plugin.
fn message_exchange_for(name: &str) -> String {
    format!("plugin.{name}")
}

/// Split a dotted namespace (`"office.gmail"`) into its ordered segments.
///
/// Empty segments are dropped, so the empty string maps to an empty list.
fn namespace_segments(s: &str) -> Vec<String> {
    s.split('.')
        .filter(|segment| !segment.is_empty())
        .map(ToOwned::to_owned)
        .collect()
}

/// Register a new plugin and all of its declared sub-records.
///
/// A fresh plugin id, JWT secret, and message-exchange binding are generated by
/// the service; the caller never supplies them.
#[derive(Debug, Clone)]
pub struct RegisterPluginRequest {
    pub name: String,
    pub description: String,
    pub scope_range: Vec<String>,
    pub server_message_signature_key: Vec<u8>,
    pub metadata: Option<PluginMetadataEntity>,
    /// `(require_plugin, require_version)` pairs.
    pub dependencies: Vec<(String, String)>,
    /// Each namespace as its ordered segment list.
    pub namespaces: Vec<Vec<String>>,
    pub tools: Vec<NewPluginTool>,
    pub skills: Vec<NewPluginSkill>,
}

/// The cluster-issued identity and credentials handed back to a freshly
/// registered plugin.
#[derive(Debug, Clone)]
pub struct RegisteredPlugin {
    pub plugin_id: Uuid,
    pub jwt_secret: String,
    pub message_exchange: String,
}

impl Processor<RegisterPluginRequest> for PluginRegistrarService {
    type Output = RegisteredPlugin;
    type Error = Error;

    #[instrument(skip_all, name = "RegisterPluginRequest", err, fields(name = %input.name))]
    async fn process(&self, input: RegisterPluginRequest) -> Result<RegisteredPlugin, Error> {
        let id = Uuid::new_v4();
        let jwt_secret = generate_secret();
        let message_exchange = message_exchange_for(&input.name);

        self.db
            .process(RegisterPluginRow {
                id,
                name: input.name,
                scope_range: input.scope_range,
                description: input.description,
                jwt_secret: jwt_secret.clone(),
                server_message_signature_key: input.server_message_signature_key,
                message_exchange: message_exchange.clone(),
                metadata: input.metadata,
                dependencies: input.dependencies,
                namespaces: input.namespaces,
                tools: input.tools,
                skills: input.skills,
            })
            .await?;

        Ok(RegisteredPlugin {
            plugin_id: id,
            jwt_secret,
            message_exchange,
        })
    }
}

/// Remove a plugin and everything that cascades from it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DeregisterPluginRequest {
    pub plugin_id: Uuid,
}

impl Processor<DeregisterPluginRequest> for PluginRegistrarService {
    type Output = ();
    type Error = Error;

    #[instrument(skip_all, name = "DeregisterPluginRequest", err, fields(plugin_id = %input.plugin_id))]
    async fn process(&self, input: DeregisterPluginRequest) -> Result<(), Error> {
        self.db
            .process(DeletePlugin {
                id: input.plugin_id,
            })
            .await?;
        Ok(())
    }
}

/// Resolve the plugin that claims a dotted namespace (`"office.gmail"`).
#[derive(Debug, Clone)]
pub struct FindPluginByNamespaceRequest {
    pub namespace: String,
}

impl Processor<FindPluginByNamespaceRequest> for PluginRegistrarService {
    type Output = Option<PluginEntity>;
    type Error = Error;

    #[instrument(skip_all, name = "FindPluginByNamespaceRequest", err, fields(namespace = %input.namespace))]
    async fn process(
        &self,
        input: FindPluginByNamespaceRequest,
    ) -> Result<Option<PluginEntity>, Error> {
        let segments = namespace_segments(&input.namespace);
        if segments.is_empty() {
            return Ok(None);
        }
        let Some(plugin_id) = self
            .db
            .process(FindPluginIdByNamespace { segments })
            .await?
        else {
            return Ok(None);
        };
        Ok(self.db.process(FindPluginById { id: plugin_id }).await?)
    }
}

/// Paginated list of registered plugins, newest first.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ListPluginsRequest {
    pub limit: i64,
    pub offset: i64,
}

impl Processor<ListPluginsRequest> for PluginRegistrarService {
    type Output = Vec<PluginEntity>;
    type Error = Error;

    #[instrument(skip_all, name = "ListPluginsRequest", err, fields(limit = input.limit, offset = input.offset))]
    async fn process(&self, input: ListPluginsRequest) -> Result<Vec<PluginEntity>, Error> {
        Ok(self
            .db
            .process(ListPlugins {
                limit: input.limit,
                offset: input.offset,
            })
            .await?)
    }
}

/// Fetch every tool advertised across all registered plugins.
#[derive(Debug, Clone, Copy, Default)]
pub struct ListToolCatalogRequest;

impl Processor<ListToolCatalogRequest> for PluginRegistrarService {
    type Output = Vec<PluginToolEntity>;
    type Error = Error;

    #[instrument(skip_all, name = "ListToolCatalogRequest", err)]
    async fn process(
        &self,
        _input: ListToolCatalogRequest,
    ) -> Result<Vec<PluginToolEntity>, Error> {
        Ok(self.db.process(ListAllPluginTools).await?)
    }
}

impl Processor<FindJwtSecretRequest> for PluginRegistrarService {
    type Output = Option<String>;
    type Error = wakuwaku::error::Error;

    #[instrument(skip_all, name = "FindJwtSecret", err, fields(plugin_id = %input.plugin_id))]
    async fn process(
        &self,
        input: FindJwtSecretRequest,
    ) -> Result<Option<String>, wakuwaku::error::Error> {
        Ok(self
            .db
            .process(FindPluginJwtSecret {
                plugin_id: input.plugin_id,
            })
            .await?)
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::{generate_secret, message_exchange_for, namespace_segments};

    #[test]
    fn generated_secret_is_48_alphanumeric_chars() {
        let secret = generate_secret();
        assert_eq!(secret.chars().count(), 48);
        assert!(secret.chars().all(|c| c.is_ascii_alphanumeric()));
    }

    #[test]
    fn message_exchange_is_plugin_prefixed() {
        assert_eq!(message_exchange_for("gmail"), "plugin.gmail");
        assert_eq!(message_exchange_for(""), "plugin.");
    }

    #[test]
    fn namespace_segments_splits_on_dots() {
        assert_eq!(
            namespace_segments("office.gmail"),
            vec!["office".to_owned(), "gmail".to_owned()]
        );
    }

    #[test]
    fn namespace_segments_empty_string_is_empty() {
        assert!(namespace_segments("").is_empty());
    }

    /// Compile-time proof that the service satisfies the exact bound the plugin
    /// auth layer injects (`Processor<FindJwtSecretRequest, Output = Option<String>,
    /// Error = wakuwaku::Error>`). If the associated types ever drift, this stops
    /// compiling instead of silently breaking `PluginMessageHook` wiring.
    #[test]
    fn service_is_a_jwt_secret_provider() {
        fn assert_secret_provider<T>()
        where
            T: kanau::processor::Processor<
                    dynamic_message_extension::plugin_message::FindJwtSecretRequest,
                    Output = Option<String>,
                    Error = wakuwaku::error::Error,
                >,
        {
        }
        assert_secret_provider::<super::PluginRegistrarService>();
    }
}
