[package]
name = "interface"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
wakuwaku = { workspace = true, features = ["tonic"] }
kanau.workspace = true
amqprs.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
ai_caller = { path = "../ai_caller" }

[build-dependencies]
tonic-prost-build.workspace = true
