[package]
name = "ai_caller"
version = "0.1.0"
edition = "2024"

[dependencies]
wakuwaku.workspace = true
kanau.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
anyhow.workspace = true
vault = { path = "../vault" }
openrouter-rs.workspace = true
reqwest.workspace = true

[dev-dependencies]
tokio.workspace = true
