[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
amqprs.workspace = true
uuid.workspace = true
sqlx.workspace = true
time.workspace = true
rand.workspace = true
wakuwaku.workspace = true
kanau.workspace = true
redis.workspace = true
tracing.workspace = true
argon2.workspace = true
tower.workspace = true
tonic.workspace = true
serde.workspace = true
sha2.workspace = true
ring = "0.17"
vault = {path = "../vault"}