[package]
name = "vault"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid.workspace = true
sqlx.workspace = true
time.workspace = true
rand.workspace = true
wakuwaku.workspace = true
kanau.workspace = true
redis.workspace = true
thiserror.workspace = true
smallvec.workspace = true
compact_str.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true