use crate::entities::db::accounts::AccountRole;
use kanau::processor::Processor;
use rand::distr::SampleString;
use time::PrimitiveDateTime;
use tracing::instrument;
use uuid::Uuid;
use wakuwaku::sqlx::DatabaseProcessor;

/// A session represents a logged-in state of a user. It is stored in Redis and used for authentication and authorization.
#[derive(Debug, Clone)]
pub struct SessionEntity {
    /// A self-incrementing serial number as primary key.
    pub serial: i64,
    pub user_id: Uuid,
    /// An indexed string used for authentication. It is generated by [generate_session_id] function and must be unique.
    pub session_id: String,
    /// The last time expire time updates.
    pub last_refreshed: PrimitiveDateTime,
    pub expires: PrimitiveDateTime,
}

/// Generate a random session ID with length of 128 characters for [SessionEntity]. The session ID is used for authentication and must be unique.
pub fn generate_session_id() -> String {
    const LENGTH: usize = 128;
    rand::distr::Alphanumeric.sample_string(&mut rand::rng(), LENGTH)
}

/// Find a [`SessionEntity`] by its bigserial primary key.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FindSessionBySerial {
    pub serial: i64,
}

impl Processor<FindSessionBySerial> for DatabaseProcessor {
    type Output = Option<SessionEntity>;
    type Error = sqlx::Error;

    #[instrument(skip_all, name = "SQL:FindSessionBySerial", err, fields(serial = input.serial))]
    async fn process(
        &self,
        input: FindSessionBySerial,
    ) -> Result<Option<SessionEntity>, sqlx::Error> {
        sqlx::query_as!(
            SessionEntity,
            r#"
            SELECT serial, user_id, session_id, last_refreshed, expires
            FROM auth.session
            WHERE serial = $1
            LIMIT 1
            "#,
            input.serial,
        )
        .fetch_optional(self.db())
        .await
    }
}

#[derive(Debug, Clone)]
pub struct FindSessionById {
    pub session_id: String,
}

impl Processor<FindSessionById> for DatabaseProcessor {
    type Output = Option<SessionEntity>;
    type Error = sqlx::Error;

    #[instrument(skip_all, name = "SQL:FindSessionById", err)]
    async fn process(&self, input: FindSessionById) -> Result<Option<SessionEntity>, sqlx::Error> {
        sqlx::query_as!(
            SessionEntity,
            r#"
            SELECT serial, user_id, session_id, last_refreshed, expires
            FROM auth.session
            WHERE session_id = $1
            LIMIT 1
            "#,
            input.session_id,
        )
        .fetch_optional(self.db())
        .await
    }
}

#[derive(Debug, Clone)]
pub struct FindUserFromSession {
    pub session_id: String,
}

#[derive(Debug, Clone)]
pub struct SessionWithUser {
    pub session_serial: i64,
    pub session_id: String,
    pub user_id: Uuid,
    pub user_role: AccountRole,
}

impl Processor<FindUserFromSession> for DatabaseProcessor {
    type Output = Option<SessionWithUser>;
    type Error = sqlx::Error;
    #[instrument(skip_all, name = "SQL:FindUserFromSession", err)]
    async fn process(
        &self,
        input: FindUserFromSession,
    ) -> Result<Option<SessionWithUser>, sqlx::Error> {
        sqlx::query_as!(
            SessionWithUser,
            r#"
            SELECT session_id, user_id, ac.role as "user_role: AccountRole", serial as "session_serial"
            FROM auth.session s
            INNER JOIN auth.account ac ON s.user_id = ac.id
            WHERE session_id = $1 AND s.expires < NOW()
            "#,
            input.session_id,
        )
        .fetch_optional(self.db())
        .await
    }
}

#[derive(Debug, Clone)]
pub struct ListUserSessions {
    pub user_id: Uuid,
}

impl Processor<ListUserSessions> for DatabaseProcessor {
    type Output = Vec<SessionEntity>;
    type Error = sqlx::Error;
    #[instrument(skip_all, name = "SQL:ListUserSessions", err)]
    async fn process(&self, input: ListUserSessions) -> Result<Vec<SessionEntity>, sqlx::Error> {
        sqlx::query_as!(
            SessionEntity,
            r#"
            SELECT serial, user_id, session_id, last_refreshed, expires
            FROM auth.session
            WHERE user_id = $1
            "#,
            input.user_id
        )
        .fetch_all(self.db())
        .await
    }
}

#[derive(Debug, Clone)]
pub struct TerminateSession {
    pub session_serial: i64,
}

impl Processor<TerminateSession> for DatabaseProcessor {
    type Output = ();
    type Error = sqlx::Error;
    #[instrument(skip_all, name = "SQL:TerminateSession", err)]
    async fn process(&self, input: TerminateSession) -> Result<(), sqlx::Error> {
        sqlx::query!(
            r#"
            DELETE FROM auth.session
            WHERE serial = $1
            "#,
            input.session_serial
        )
        .execute(self.db())
        .await?;
        Ok(())
    }
}

#[derive(Debug, Clone)]
pub struct TouchSession {
    pub serial: i64,
    pub expires: PrimitiveDateTime,
}

impl Processor<TouchSession> for DatabaseProcessor {
    type Output = ();
    type Error = sqlx::Error;
    #[instrument(skip_all, name = "SQL:TouchSession", err)]
    async fn process(&self, input: TouchSession) -> Result<(), sqlx::Error> {
        sqlx::query!(
            r#"
            UPDATE auth.session
            SET last_refreshed = now(), expires = $2
            WHERE serial = $1
            "#,
            input.serial,
            input.expires
        )
        .execute(self.db())
        .await?;
        Ok(())
    }
}

#[derive(Debug, Clone)]
pub struct CreateSession {
    pub user_id: Uuid,
    pub session_id: String,
    pub created_at: PrimitiveDateTime,
    pub expires: PrimitiveDateTime,
}

impl Processor<CreateSession> for DatabaseProcessor {
    type Output = SessionEntity;
    type Error = sqlx::Error;
    #[instrument(skip_all, name = "SQL:CreateSession", err)]
    async fn process(&self, input: CreateSession) -> Result<SessionEntity, sqlx::Error> {
        sqlx::query_as!(
            SessionEntity,
            r#"    
            INSERT INTO auth.session
            (user_id, session_id, last_refreshed, expires) VALUES ($1, $2, $3, $4)
            RETURNING serial, user_id, session_id, last_refreshed, expires
            "#,
            input.user_id,
            input.session_id,
            input.created_at,
            input.expires,
        )
        .fetch_one(self.db())
        .await
    }
}
